#!C:\Users\wania\OneDrive\Documents\Semester-8 (FAST)\Agentic AI\Agentic Project\AI-Powered-Animated-Video-Generation-System\agenticproj\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
